include = ["string","cstdint"]
namespace = "Game"
struct_name = "Player"
compare = true
copy = true
[[member]]
name = "name"
type = "std::string"
[[member]]
name = "id"
type = "uint16_t"
initial = 0
[[member]]
name = "level"
type = "uint16_t"
initial = 1
[[member]]
name = "exp"
type = "uint32_t"
initial = 0
[[member]]
name = "nb_battle"
type= "uint32_t"
initial = 0
[[member]]
name = "pos"
type = "Position"
    [[member.Position]]
    name = "x"
    type = "float"
    initial = 0.0
    [[member.Position]]
    name = "y"
    type = "float"
    initial = 0.0
[[member]]
name = "life"
type = "bit-unsigned"
bits = 10
initial = 100
[[member]]
name = "hp"
type = "bit-unsigned"
bits = 10
initial = 100
[[member]]
name = "healing"
type = "bit-unsigned"
bits = 4
initial = 9
[[member]]
name = "attack"
type = "bit-unsigned"
bits = 10
initial = 10
[[member]]
name = "defence"
type = "bit-unsigned"
bits = 10
initial = 7
[[member]]
name = "agility"
type = "bit-unsigned"
bits = 7
initial = 5
